mqtt:
  enabled: False

cameras:
  cam:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:1337/cam
          roles:
            - detect
            - record
      hwaccel_args: preset-rpi-64-h264
    detect:
      enabled: True
      width: 640
      height: 480
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - bottle
    - wine glass
    - cup



